### ISSUE TITLE
[Thunderstore page] readme doesnt show images

### ISSUE THREAD

**Issue by CatsArmy** [Kesomannen/gale#1]
it should be as simple this:
doesn't have the ```?raw=true``` as the github page doesnt have it but github isnt dumb about this at least but yeah

> for example this:
> ```![screenshot](/images/screenshot1.png)```

results in this:
![screenshot](/images/screenshot1.png)

> and it should actually be this:
> ```![screenshot](https://github.com/Kesomannen/gale/blob/master/images/screenshot1.png?raw=true)```
> ```?raw=true``` is important for it to actually display the image

results in this:
![screenshot](https://github.com/Kesomannen/gale/blob/master/images/screenshot1.png?raw=true)

btw this project looks amazing, though i am having some trouble with profile codes and stuff but im sure it will get better

**Comment by Kesomannen** [comment]
Alright thanks, was looking for a fix for this
