### ISSUE TITLE
Gale no longer working at all in latest version

### ISSUE THREAD

**Issue by Test-Account666** [Kesomannen/gale#104]
Hey!

Gale completely stopped working for me.

Here's a screenshot:
![grafik](https://github.com/user-attachments/assets/06a05066-b889-41ac-b284-e4f28ad12f8a)

**Comment by Kesomannen** [comment]
Huh, that shouldn't stop it from starting

**Comment by Test-Account666** [comment]
> Huh, that shouldn't stop it from starting

That error isn't the cause. 

Also appeared in the last version. 

It also fetches all mods from TS just fine. 

Basically just the UI stopped working

**Comment by Kesomannen** [comment]
This is a bit stale and seems specific to you, so I'll close it now. If you find any more information, feel free to reopen it
