### ISSUE TITLE
[Suggestion] Improve profile imports

### ISSUE THREAD

**Issue by CatsArmy** [Kesomannen/gale#106]
when i try to import a profile with a mod that is local or from a different community the import just fails.
i suggest perhaps when importing a profile:
create a list/queue/stack.
whenever a mod isn't found/successfully downloaded ignore it and add it to the list.
at the end of the import display the list of mods that failed to import.

**Comment by CatsArmy** [comment]
also when importing a local mod the mod count of the profile doesn't increase

**Comment by Kesomannen** [comment]
Local mods importing from profiles is not supported due to security reasons.

If you import a code from a different community, *all* the mods (except for maybe BepInEx) will fail, so I don't see how a list would help there.

**Comment by CatsArmy** [comment]
I think you misunderstood it or just aren't aware of some of the plugins that work across games. 

To start off I suggested displaying a list so the user doesn't have to start looking at all the mods in their profile and find the ones that didn't import.
This is especially useful for debugging and developing mods. here's a personal recent experience I had while creating a custom weapon for ROUNDS. I was casually trying to test the networking of the mod so I saw that gale supports direct launch mod unlike other mod managers so I went and imported my r2 profile and then bang nothing happened so I looked at my profile and noticed that me disabling the local mods did not do anything to let me import the profile.(Local mods: my rounds mod)(LC mods: Yukieji Unity explorer(maintained fork of the og Unity explorer). I was a bit confused by that point.
I was expecting gale to import the profile like normal but keep the mods it couldn't find in the current community in a list that would then help you know what failed and needed manual importing.

e.g when I try to import a profile in the ROUNDS community which looks like this:
Roundlib1,
Roundlib2,
Roundspatches,
Mylocalmod,
LC-YukiejiUnityExplorer.

I would expect the profile to import all of the rounds mods and display: $"Are you sure you want to install mods/(a mod):{other_community_mods.DisplayList()} from a different community? This could result in unexpected behaviors and even errors opening the game". And after that popup I would expect it to display: $"Couldn't import local mod/mods:{local_mods.DisplayList()} if you need these mods please import them manually/n/n (Button) if you aren't sure why your seeing this and or what this means and or don't care disable local mod notifications by clicking this".

**Comment by CatsArmy** [comment]
I personally see gale as the new manager default for modding and developing mods. It has 99% of the r2/thunderstore features and even more features and many of them make developing mods much easier like the direct launch mode and more. 
But it is missing this feature I have suggested and also the ability to redownload/downgrade(I think I don't remember) a installed mod this is useful for 2 reasons:
1. Fixing corrupted files that failed when installing. 
2. Removing a local .dll or any other file of the mod used for development without having to uninstall the mod and then reinstall it just to test the current published version of the mod.

**Comment by CatsArmy** [comment]
I really do believe you should ask the user if they don't want the info of the mods that were unable to be imported smoothly because it could really help with the headache that is importing development/beta testing profiles

**Comment by CatsArmy** [comment]
Also just a lil bit of feedback it is really annoying when you try and disable/enable a mod and accidentally click the mod itself then displaying the readme and more which then moves the entire mod list bar to the left which makes you go back to the middle of the app now and then you try to click it again or disable/enable it and then you miss again and it goes right back to the right of the screen

**Comment by CatsArmy** [comment]
> Local mods importing from profiles is not supported due to security reasons.
> 
> If you import a code from a different community, *all* the mods (except for maybe BepInEx) will fail, so I don't see how a list would help there.

Again never in this issue have I asked for support to import local mods. I asked for displaying mods that could be imported from other communities and mods that couldn't be found at all
