### ISSUE TITLE
BepInEx is not pinned to top when sorted by descending install date

### ISSUE THREAD

**Issue by Flamy2000** [Kesomannen/gale#108]
When sorted by descending install date, BepInExPack will be pinned at the bottom.
When sorted by ascending install date, BepInExPack will be pinned at the top.
This differs from all other sorts, where BepInExPack is always pinned to the top.

**Comment by Kesomannen** [comment]
This is intended; when sorting by install date or "custom", pins are ignored. The reason for BepInEx's position in the list is because it was installed first.
