### ISSUE TITLE
Freeze when alt-tabbing

### ISSUE THREAD

**Issue by McAwesome123** [Kesomannen/gale#115]
The mod manager occasionally stops responding after alt-tabbing.
Whenever this happens, it needs to be force closed through task manager or the not responding popup.

**Comment by TianMengLucky** [comment]
Unable to reproduce the same situation

**Comment by Kesomannen** [comment]
Do you have any more information? Is it still happening?

**Comment by Kesomannen** [comment]
stale

**Comment by McAwesome123** [comment]
I am still having this issue.
If I press alt and tab a bit apart, it doesn't seem to happen
but if I press them at the same time, it seems to happen relatively consistently.
