### ISSUE TITLE
Risk of Rain 2 isn't launching?

### ISSUE THREAD

**Issue by fnmeowskulls** [Kesomannen/gale#117]
For some reason, specifically Risk of Rain 2 stopped launching mods. The game launches, just no console, no risk of rain 2 console, nothing.
Not sure what is causing it, but maybe directories, everything seems in order though, so I'm stumped.

**Comment by Kesomannen** [comment]
Huh. Have you tried both steam and direct launch mode?

**Comment by Kesomannen** [comment]
I'm gonna close this as stale, feel free to open it again if the issue persists
