### ISSUE TITLE
Cannot download modpack

### ISSUE THREAD

**Issue by PureFPSZac** [Kesomannen/gale#12]
I cannot add my own modpack to a profile on gale, downloading it on r2 works completely fine. I don't know what this dependency is, it doesn't even show on the list when you look at the dependencies. 
![image](https://github.com/Kesomannen/gale/assets/27163571/b46aaf38-6d7d-4f60-ba03-fd9fcbe650ba)

**Comment by PureFPSZac** [comment]
I found the issue, one of my dependencies (SuitsAndCosmetics) for some reason has bbepis as a dependency instead of BepInEx. Both R2 and the Thunderstore client has no issue ignoring the not found dependency and just downloading the mod anyway. Any chance you could do that? The people who use my pack quite like the cosmetics that the mod adds and I don't want to have to remove for people (myself included) who want to use Gale

**Comment by Kesomannen** [comment]
Seems like r2modman also doesn't find it, but let's you download it anyway.

![bild](https://github.com/Kesomannen/gale/assets/113015915/6a06f28c-5b54-4498-8668-0c91abda5ee0)
![bild](https://github.com/Kesomannen/gale/assets/113015915/a4e3320a-84c5-4a08-acb1-a5a8e2e7b123)

I'll add a warning about missing dependencies in the next version.

**Comment by PureFPSZac** [comment]
Thanks! Excited for the update. Gale seems amazing so far. You've done a fantastic job :)
