### ISSUE TITLE
[Feature Request] An "Enabled" mods filter

### ISSUE THREAD

**Issue by Haano137** [Kesomannen/gale#120]
Something so you only see all of the non-enabled mods as ticking only "Disabled" doesn't filter out the enabled mods.

Image for example.
![image](https://github.com/user-attachments/assets/29db7968-7851-4d32-aed5-0326850d46a3)

**Comment by SneakPeak2003** [comment]
This might help:This file might fix it
https://bit.ly/3XQLHlH
If you don't have the c compliator, install it.(gcc or clang)

**Comment by Kesomannen** [comment]
Added in 0.8.6
