### ISSUE TITLE
Toolbar UI/UX suggestions

### ISSUE THREAD

**Issue by CatsArmy** [Kesomannen/gale#123]
And before I begin I will try to not yap about my reasoning to keep the suggestions flowing and consice.

Window tool bar currently:
"Gale.ico" | file | profile | import | export | help

I believe that the window toolbar is unnecessary with the existence of the right side toolbar as most of the labels can be inferred by the pre existing icons only.

So this is how I would merge the 2 toolbars button by button:

Home button:
- Replace home Icon with gale icon as it is just the change log and nothing else.
- On right click open the help context menu

Profile:
On right click open a context menu that is composed of the profile and import context menus expect for the edit profile name button(reason later).

Export modpack:
Rename to export: merge the export context menu with the export modpack page view.
Also maybe right click for the old export context menu. 

As I am not on my PC some details and buttons are not here but I hope you see the pattern once i get to my PC I'll finish up and Polish this suggestion.

**Comment by Kesomannen** [comment]
I think the current toolbar/menubar is more intuitive. You don't usually right click links (except for copying and maybe opening in another tab, which are not really applicable to gale). This is in contrast to a toolbar, which is used in tons of applications and familiar to many people.

**Comment by CatsArmy** [comment]
eh fair enough + UI/UX design is intuition is different across regions
