### ISSUE TITLE
Can't import or delete local mod

### ISSUE THREAD

**Issue by slayer6409** [Kesomannen/gale#126]
It just gives:
`Failed to import local mod - Invalid args `path` for command `import_local_mod`: command import_local_mod missing required key path.`

**Comment by Gaodust** [comment]
Still happening with the latest version that released today.

**Comment by Kesomannen** [comment]
You sure you're on 0.8.9? It works fine for me

**Comment by slayer6409** [comment]
Seems to be fixed with 0.8.9 for me

**Comment by Kesomannen** [comment]
This is a bit stale so I'll just assume it got fixed
