### ISSUE TITLE
Manager opens an empty box then closes and stays in background.

### ISSUE THREAD

**Issue by SlimeBind** [Kesomannen/gale#131]
First time using this, when its launched, it opens a blank box for a split second then closes the window immediately.
After that it stays running in the background, ranking up some memories up to 400-700 MBs before staying at that number.

Am using the latest version (0.8.9) and have tried some older versions leading the same result.
The com.kesomannen.gale folder also gets created with the .json files but nothing seem be in the latest.log file.

**Comment by Kesomannen** [comment]
Try installing WebView2 Runtime
