### ISSUE TITLE
[Suggestion | profile tab tweak] right clicking mods 

### ISSUE THREAD

**Issue by CatsArmy** [Kesomannen/gale#135]
# At the moment right clicking mods in the profile does nothing.

## When you want to do anything to a mod<sub>(beside reordering it and disabling it.)</sub> you have to: 
1. left click the mod.
2. find the three dots, (2.5) and click them.
3. find the menu item you want, (3.5) and click it.

## that's can be reduced to a simple right click that shows the same context menu instead of nothing.
i am in no way saying you should remove the three dots, they are useful in their own right but right clicking can help improves the user work flow.

Side notes: you should also probably add to the three dots context menu the option to visit the thunderstore listing of the mod. atm it only has the Website the mod added to their manifest file.

also why is there an option to see the change log when there is no change log found
![image](https://github.com/user-attachments/assets/c126f48c-f691-44e0-8988-4ce11bd0f7be)
i would just hide the button unsure of how that could be done in the code but if that's annoying to implement then fuck that's not worth it.

**Comment by Test-Account666** [comment]
I also think a context menu would be nice.

Easier/Faster to uninstall multiple mods for example

**Comment by Kesomannen** [comment]
This is coming soon 👍

The changelog is the way it is because gale can't know if there is one or not without actually sending the request.

**Comment by Kesomannen** [comment]
Added with 0.9.0
