### ISSUE TITLE
Increase the visiblity of config categories that have an empty name

### ISSUE THREAD

**Issue by isolno** [Kesomannen/gale#136]
Config category sections with an empty string name (in file it will be '[]') will have a much smaller height in the interface, making it very easy to miss. In attached image is an empty string category being hovered over.
![emptyexample](https://github.com/user-attachments/assets/588d0551-f534-4f90-a50a-dcf866871a7b)

**Comment by Kesomannen** [comment]
Fixed in 0.9.0
![bild](https://github.com/user-attachments/assets/01f7b7f8-c345-4131-b157-02e11c387cf7)
