### ISSUE TITLE
Manifest file error when importing a local mod

### ISSUE THREAD

**Issue by LordVGames** [Kesomannen/gale#138]
regardless if it's a hand edited manifest, a manifest from a mod manually downloaded or even the r2boilerplate manifest, any manifest file will cause this error:
`Failed to import local mod - Failed to read manifest: expected value at line 1 column 1.`
when trying to import a local mod with the exact same manifest into r2modman, it works just fine.
i'm also using 7-zip to create the mod's zip file that i import.

here's the r2boilerplate manifest file if you want to test against it:
[manifest.json](https://github.com/user-attachments/files/17467339/manifest.json)

**Comment by Kesomannen** [comment]
Should be fixed with 0.9.1
