### ISSUE TITLE
[Suggestion] New sorting options

### ISSUE THREAD

**Issue by SeymourSchlong** [Kesomannen/gale#14]
![image](https://github.com/Kesomannen/gale/assets/36908123/2bc59d74-d4b4-40a9-a94c-916867baa316)

R2 has the ability to sort by `Author name` and `Mod name` which I appreciate for finding specific mods (ignoring the search bar, of course).

**Comment by Kesomannen** [comment]
Coming in the next update, along with other changes to sorting and filtering
