### ISSUE TITLE
Small Issues Thread

### ISSUE THREAD

**Issue by CatsArmy** [Kesomannen/gale#140]
i found a couple of little issues so instead of creating an issue for each one ima do it this way:

![image](https://github.com/user-attachments/assets/a531d2ac-53ff-45c5-9a37-310d1eb08a70)
![image](https://github.com/user-attachments/assets/33af000f-f943-4836-8abf-92b1700b8482)
all shortcut key bind text thingy should be spaced out like so {modifier} + {key} instead of {modifier}+{key} for better visual clarity.
also the zoom in key bind doesn't work.

the window toolbar context menu is a bit repetitive when we have the:
![image](https://github.com/user-attachments/assets/1ba789d5-a5b9-41a7-94b0-63cbd80cea59)
these buttons:
![image](https://github.com/user-attachments/assets/fb979973-d1d5-4e43-9716-c6a7beddf4fb)

there are no visual indicators other than hovering that indicate this is a hyperlink
![image](https://github.com/user-attachments/assets/51f254c5-b11f-41c9-bbb0-23ab12f07386)

does gale support modding games from the epic games library? the context menu doesn't have an option for that it only has steam and direct which is a bit confusing
![image](https://github.com/user-attachments/assets/fc1f9de3-231a-4da8-b781-78704e5c4994)

thoughts on this potential tweak:
![image](https://github.com/user-attachments/assets/c27c732d-ea48-42db-8ca7-ea320e1abed0)
![image](https://github.com/user-attachments/assets/6b9b1652-a3de-493e-bbb3-b357237fd5d6)
?

**Comment by Kesomannen** [comment]
> the window toolbar context menu is a bit repetitive when we have the:

Yeah I might remove those. Honestly, I just wanted to populate that menu more.

> there are no visual indicators other than hovering that indicate this is a hyperlink

I know a lot of people have missed this, but I can't think of a good way to fix it. I could add an underline, but that would be inconsistent with the rest of the app, as well as being a bit ugly. Could also add an item to the context menu which goes to the thunderstore page, although that would add some redundancy.

> does gale support modding games from the epic games library? the context menu doesn't have an option for that it only has steam and direct which is a bit confusing

It does not, but could be added in the future. Although it feels like the number of people who would use that is really small.

> thoughts on this potential tweak:

I'm guessing you want that edit button to let you rename the profile. I've thought about doing something similar, but I think it would get too crowded and probably warrant a whole dialog instead of just a dropdown. That would however make changing profiles slightly more bothersome, which is a much more common action that renaming.

**Comment by CatsArmy** [comment]
> > does gale support modding games from the epic games library? the context menu doesn't have an option for that it only has steam and direct which is a bit confusing
> 
> It does not, but could be added in the future. Although it feels like the number of people who would use that is really small.

understandable yeah just wanted to know. that would probably be 1.x.y feature. for now id change mention that somewhere in the readme or something.
___________

> > the window toolbar context menu is a bit repetitive when we have the:
> 
> Yeah I might remove those. Honestly, I just wanted to populate that menu more.

fair enough its understandable.
___________

> > thoughts on this potential tweak:
> 
> I'm guessing you want that edit button to let you rename the profile. I've thought about doing something similar.

i just wanted a button that would let me rename the profile, it doesn't have to make the name into a text edit box
it could just simply be the same as pressing f2 but on a specific profile.
![image](https://github.com/user-attachments/assets/570c372e-9b4c-4c60-9fbe-3e70054b1227)
>but I think it would get too crowded and probably warrant a whole dialog instead of just a dropdown.

to address it being too crowded i thought you could just increase the length of the profile select button + dropdown to be wider or even resizable(unlikely and probably unwanted).

why would that require a dialog i mean it already has a delete button cant it be just another button like that(i have never used tauri before)


> That would however make changing profiles slightly more bothersome, which is a much more common action that renaming.

why is that? i don't see how a edit name button could make it more bothersome if it isn't too crowded

________
> ![image](https://private-user-images.githubusercontent.com/104517593/378823835-a531d2ac-53ff-45c5-9a37-310d1eb08a70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3MDEwODMsIm5iZiI6MTcyOTcwMDc4MywicGF0aCI6Ii8xMDQ1MTc1OTMvMzc4ODIzODM1LWE1MzFkMmFjLTUzZmYtNDVjNS05YTM3LTMxMGQxZWIwOGE3MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyM1QxNjI2MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZjYxNGE5ZDUxMDRlMjViMGNkOWM3YWU3ZjM5MWQ5YmY0ZDYyZDk0OTNiY2I0NjVmOTIxZDI1NGM3OTY2NzVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.A_J4tjY2P1bDRp1NKHlYu0yH6aG2BFiqXeKWyUgMxAA) ![image](https://private-user-images.githubusercontent.com/104517593/378823854-33af000f-f943-4836-8abf-92b1700b8482.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3MDEwODMsIm5iZiI6MTcyOTcwMDc4MywicGF0aCI6Ii8xMDQ1MTc1OTMvMzc4ODIzODU0LTMzYWYwMDBmLWY5NDMtNDgzNi04YWJmLTkyYjE3MDBiODQ4Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyM1QxNjI2MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYjY0NGMzYWIyYTdhNjdhMWI5NWQwZDIwYTQwYTNjN2RjOGEzMzBhY2U3MWUzYjMwNTMwYmNmOTFjMjhhZDA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.B3f5OmjGSYYmdQCaqtU7bL-YQXuPBU66mp4pPfSXjyU)
all shortcut key bind text thingy should be spaced out like so {modifier} + {key} instead of {modifier}+{key} for better visual clarity. also the zoom in key bind doesn't work.

^ ?
___________
also is this normal behavior for deleting profiles?
> ![image](https://github.com/user-attachments/assets/e0a98b31-031e-4834-b9fc-3d05c09c2ac2) ![image](https://github.com/user-attachments/assets/69fb3f4f-00b1-4247-a24a-007b2d2363e1)

**Comment by Kesomannen** [comment]
> why would that require a dialog i mean it already has a delete button cant it be just another button like that(i have never used tauri before)

I mean the profile selection dropdown itself. Making it wider is an option I probably should have considered earlier xD Might add the rename button in the next update

> also is this normal behavior for deleting profiles?

Yeah, to prevent you from deleting profiles by mistake.

**Comment by CatsArmy** [comment]
> > also is this normal behavior for deleting profiles?
> 
> Yeah, to prevent you from deleting profiles by mistake.

well yeah but i dont know if im just crazy or is it a different confirmation dialog then the rest of the app.
i just checked yes i am crazy that is the normal dialog gale uses it seems i thought it would be app native and not OS native dialog but it doesnt matter i guess lol

**Comment by Kesomannen** [comment]
Most of the stuff here is implemented in some way now, so I'll close this
