### ISSUE TITLE
Version 0.9.0 lacks the option to change the version of a mod that has already been downloaded

### ISSUE THREAD

**Issue by AlanCratys** [Kesomannen/gale#142]
In the current latest version 0.9.0, downloaded mods cannot switch versions, which is very unfavorable for configuring modpacks and cannot be compared to exclude some problems caused by updating mods. It is very inconvenient.
I think the version switching function of the downloaded mod is very important for me to continue adding it again.

**Comment by Kesomannen** [comment]
Sorry about that, I'll get it back ASAP

**Comment by Kesomannen** [comment]
Readded with 0.9.1
