### ISSUE TITLE
[Zoom in] hotkey doesn't work 

### ISSUE THREAD

**Issue by CatsArmy** [Kesomannen/gale#143]
I'm unsure this is a me issue or if anyone else is unable to press ctrl | + to zoom in.
i would like to know if it is working for anyone?

just so its clear any other hotkey works perfectly fine.
i can zoom out and reset zoom and rename profile and all of that but for some reason it doesn't work with the zoom in. i even searched the code for where it is listening and reacting to the hotkey

To reproduce bug:
### press `ctrl +`
(not the menubar > window > zoom in)

________
also by the way when you use the zoom hotkeys while in the settings/prefs page the `Zoom factor: {value}` doesn't update the displayed value. I'm unsure if this is a limitation with the framework of the app.

**Comment by Kesomannen** [comment]
Fixed with 0.9.2

**Comment by CatsArmy** [comment]
Ok so now i am starting to think this really is a me issue because i just updated and it still is happening to me REEEEEEEEEEEEEEEEEEE
