### ISSUE TITLE
[Bug] Gale is adding a "=" sign to empty String config values.

### ISSUE THREAD

**Issue by broken-usb** [Kesomannen/gale#144]
Sometimes when leaving a String value empty, Gale will add a = to said config value:
![image](https://github.com/user-attachments/assets/654ec8f8-d064-4395-8b89-c1cdf4a920c5)
![image](https://github.com/user-attachments/assets/cad3a458-bf4a-43d7-8990-93a66199e8fb)
![image](https://github.com/user-attachments/assets/53a24972-d7eb-4dfd-9965-577a2f721c14)
The config shown in the screenshots is from [Cull Factory](https://thunderstore.io/c/lethal-company/p/fumiko/CullFactory/).

**Comment by Kesomannen** [comment]
Fixed with 0.9.2
