### ISSUE TITLE
[Bug] Importing to r2modman or Thunderstore Fails/Publishing Exporting Fails

### ISSUE THREAD

**Issue by ngj5-beasTxx** [Kesomannen/gale#146]
When I export a file or code from Gale then import using using r2modman or Thunderstore no mods actually get installed. The code or file are always accepted by r2modman or Thunderstore. For example when importing into r2modman the mods to be imported are listed but when it's done importing none are actually installed. I'm also unable to publish a mod pack to the Thunderstore or export it as a file too.

I've uploaded a video below of both issues I'm experiencing. As for Thunderstore I don't have it installed but per my friends they experience the same behavior as r2modman in the video. 

https://github.com/user-attachments/assets/9a1e1f4b-b87e-48e0-83b5-eae875512872

Any suggestions would be beneficial but for now I have switched back to r2modman. 

Specs:
OS: Microsoft Windows 10 Enterprise LTSC 2021 (x64)
Gale: 0.9.2
r2modman: 3.1.51

**Comment by Kesomannen** [comment]
This is an issue with the latest update of r2modman
