### ISSUE TITLE
OS error 17 when trying to import a mod list from r2modman onto any drive other than C:/

### ISSUE THREAD

**Issue by mujahidean1** [Kesomannen/gale#152]
I'm on Windows 10 x64, fully up to date. I've tried importing from code and from file, running as admin, installing Gale on different drives, purging and moving the data folder to any other drive, but importing never works due to this error. Like, even if Gale and the Data folder are both on the B:/ drive I get this error, but if Gale is on D:/ but the data folder is the default one on C:/ it will work.

Obviously it's an OS error and something to do with system links so at first it seems like a system issue, but this is literally the only program that's ever given me this error and both r2modman and tsmodman can import modlists to any drive just fine. I don't have the space on my C drive to try downloading them there and then moving the data directory unfortunately.

**Comment by Kesomannen** [comment]
What is the error exactly?
