### ISSUE TITLE
[Bug] Freeze after clicking on Export modpack for some games

### ISSUE THREAD

**Issue by starfi5h** [Kesomannen/gale#153]
In some games, clicking on the "Export mod pack" button will cause the mod manager to stuck on a blank page, and other buttons will also stop responding.
![image](https://github.com/user-attachments/assets/1b8a76e3-7548-44e9-915d-3d4905ba3fe7)
Mod manager version: 1.0.1
OS: Win10

Here are game communities that have this issue:
- Bonelab
- Dyson Sphere Program
- Subnautica
- Talespire

I suspect it has something to do with 'modpacks' category doesn't exist in those communities on Thunderstore.

**Comment by Kesomannen** [comment]
Fixed with 1.1.0
