### ISSUE TITLE
[FEATURE REQUEST] CLI mod installation

### ISSUE THREAD

**Issue by cyaneko** [Kesomannen/gale#158]
Moving over from r2modman.
Currently, I've been using VS post-build steps to automatically install locally developed mods to a selected profile of my choice for testing. Would it be possible to implement a CLI interface to do this natively with just one command taking the profile name and the path to the mod zip?

**Comment by Kesomannen** [comment]
I'll try to get this in the next update. The way you'd use it is:

```
./gale.exe --game lethal-company --profile Default --install "path/to/zip" (--no-gui)
```

and it overrides any local mods with that same name. Does that sound good?

**Comment by Kesomannen** [comment]
Added it in 1.1.3, I'll update the wiki soon

**Comment by cyaneko** [comment]
Does not seem to work as intended.

Command used is `"C:\Program Files\Gale\gale.exe" --game touhou-lost-branch-of-legend --profile "Default" --install "$(ProjectDir)$(AssemblyName)-thunderstore.zip" --no-gui`

When running the command, the GUI still pops up, the application hangs, needs to be force killed, and nothing is installed.

![obraz](https://github.com/user-attachments/assets/fa127b04-d224-49f1-a957-f2996485d8eb)
![obraz](https://github.com/user-attachments/assets/f2f6df40-8775-49ee-b513-66727c0408b5)

**Comment by Kesomannen** [comment]
Oh weird it does the same for me. It worked fine in the debug build though.

**Comment by cyaneko** [comment]
`--no-gui` seems to make the mod installation fail, with this error:
![obraz](https://github.com/user-attachments/assets/db478667-9d6c-46a6-88ab-55b9cf33bdd4)

If I omit it, it installs just fine.
