### ISSUE TITLE
[1.1.0] Failed to launch: Failed to read profile manifest

### ISSUE THREAD

**Issue by u-lulu** [Kesomannen/gale#159]
Upon updating to 1.1.0, I am unable to launch Gale, and am presented with the following error:
![image](https://github.com/user-attachments/assets/361cbfda-d245-46ab-a3b1-1cef2ecb6d00)

The profile in question launched and ran fine before this update.
For convenience, here is the profile (**with the BepInEx/plugins folder excluded** to reduce filesize): 
[Gurt Gang Gearbox Edition.zip](https://github.com/user-attachments/files/17737504/Gurt.Gang.Gearbox.Edition.zip)

**Comment by u-lulu** [comment]
I was able to resolve this issue by downgrading to 1.0.1, exporting my RoR2 profiles, updating back to 1.1.0, and reimporting them. However, I will leave this issue open as I believe this is still a bug.

**Comment by PyroTech03** [comment]
Same issue.  Does export/Import keep the Modpack continuity?  I had to do a reimport before due to other issue and it broke my modpack builder.

**Comment by u-lulu** [comment]
> Same issue.  Does export/Import keep the Modpack continuity?  I had to do a reimport before due to other issue and it broke my modpack builder.

I'm not sure what you mean by continuity, but it should preserve pretty much everything you need. The only extra thing I needed to do after reinstalling Gale was setting the game directory in the settings again.

**Comment by PyroTech03** [comment]
The changelog for me when I did a reimport broke. Had to do a big copy/paste thing with it. Was just a pain to work with.

**Comment by Kesomannen** [comment]
This is due to some thunderstore mod names that have more than 3 hyphens, which I didn't know was allowed. I'll get a fix out as soon as possible, but you'll have to update manually unfortuantely

**Comment by Kesomannen** [comment]
> Does export/Import keep the Modpack continuity?

Since the import/export uses r2modman's format it can't preserve the modpack export data sadly.

**Comment by Kesomannen** [comment]
This is fixed with 1.1.1
