### ISSUE TITLE
Webfishing displays Lethal Company mods after scrolled down far enough

### ISSUE THREAD

**Issue by TesterHere06** [Kesomannen/gale#160]
![image](https://github.com/user-attachments/assets/f1751ba9-87d6-4aef-aed4-b0a017993597)

**Comment by TesterHere06** [comment]
It appears to happen if you switched to another game and then back

**Comment by Kesomannen** [comment]
I can't replicate this 🤔

**Comment by Kesomannen** [comment]
No matter what I try I can't get it to reproduce, so I'll close this for now
