### ISSUE TITLE
[1.1.0] Failed to launch Gale. OS error 2

### ISSUE THREAD

**Issue by Uproaring** [Kesomannen/gale#162]
![image](https://github.com/user-attachments/assets/ae7fb6a7-7891-42e7-9843-6661815d64ea)
crashes upon launch

**Comment by LeoRH123** [comment]
Same crash

**Comment by AlanCratys** [comment]
![image](https://github.com/user-attachments/assets/e894f26f-de3b-476e-a003-f9231615a96c)
yep

**Comment by Kesomannen** [comment]
Delete the among-us folder under gale's data folder. I'll fix this in the next update. 

The other error is a different issue, see #159
