### ISSUE TITLE
duplication of .cfg files

### ISSUE THREAD

**Issue by thundershocker1** [Kesomannen/gale#163]
For some reason, when downloading a modpack (and possibly any mod), it'll create a .cfg file with the correct configs, then an additional one with the default configs.
![IMG_5490](https://github.com/user-attachments/assets/a1581ad7-51d4-4b74-af86-9754a19566d9)
![IMG_5489](https://github.com/user-attachments/assets/6017dc7a-2290-4510-8572-c557ec022b32)

**Comment by Kesomannen** [comment]
This is fixed in 1.1.1, but your profiles and mod cache will still be invalid. To fix it you can 

1. export the profile(s) to code(s)
2. clear you unused mod cache (under the File menu)
3. import the profiles again

and remember to also update
