### ISSUE TITLE
1.1.0 broke everything

### ISSUE THREAD

**Issue by OWER396** [Kesomannen/gale#165]
After updating to 1.1.0 Gale crashes and I get this message
![galeerror](https://github.com/user-attachments/assets/5a638d8b-53f0-40f5-9115-57978a1b4e2f)
Deleting that specific modpack didn't fix it, however deleting the whole appdata folder fixed it. 1.1.1 didn't fix it either

**Comment by Kesomannen** [comment]
Do you still have a code/file for that profile?

**Comment by OWER396** [comment]
Yes, it seems to work fine after deleting the appdata folder though.

Here's the code: 019198e1-7a19-ea83-6f7f-b30c1217ed18

**Comment by Kesomannen** [comment]
Welp, happy that it works. The codes does seem completely fine, I guess it was something corrupted/invalid about the profile on your disk, but I guess we'll never find out.
