### ISSUE TITLE
Friend can't import profile due to missing name field in the profile manifest

### ISSUE THREAD

**Issue by LordVGames** [Kesomannen/gale#166]
we're both on version 1.1.1 and the profile name on both my end and my friends end have no weird characters. this also happens with a file export so i'll attach it here to test with it, remove the .zip from the name before importing since github doesn't let me upload .r2z files

![broke](https://github.com/user-attachments/assets/c86e633e-99ec-43fa-9b2b-3d251ae94f14)

[Lords Starstorm 2.r2z.zip](https://github.com/user-attachments/files/17757829/Lords.Starstorm.2.r2z.zip)

**Comment by Kesomannen** [comment]
Try updating to 1.1.2

**Comment by LordVGames** [comment]
yeah it was fixed by either 1.1.2 or 1.1.3
