### ISSUE TITLE
Updating a mod leaves the previous version in the mod list with an update icon

### ISSUE THREAD

**Issue by JarheadHME** [Kesomannen/gale#169]
![image](https://github.com/user-attachments/assets/2a9bff57-8536-4f0d-a4f8-b7fa127218a7)
I had 1.4.1 in the screenshot before, and upon updating, 1.5.0 was added to the mod list. The actual mod in the plugins folder seems to be 1.5.0, but 1.4.1 is still in the mod list, even after restarting the entire system. Trying to toggle 1.4.1 off very briefly ticks the 1.4.1 checkbox, then it immediately switches back over, while the checkbox will properly toggle 1.5.0

**Comment by Kesomannen** [comment]
This doesn't happen for me, any other steps that might help to replicate it?

**Comment by JarheadHME** [comment]
This unfortunately hasn't happened very consistently, but the profile I have this issue on currently, it's still there. Is there some fashion I can get some sort of debug information, or some way to look at it to you? I've joined the discord server if contact there would be easier, but whatever is preferred!

**Comment by JarheadHME** [comment]
I can't verify this easily, but the one possible lead I can think of, is I _think_ the mods this happened to had updates come out while Gale was still open. Again though, I'm not certain, I didn't think too hard about what I'd done the first time it happened thinking it was a one-off, and it was only once it happened again this more recent time that I came to bring it up

**Comment by Kesomannen** [comment]
I just realized that if the uninstallation of the previous version fails, Gale still continues with the update, which probably happened on these occasions.

**Comment by Kesomannen** [comment]
That fix is out in 1.1.3 so I'll close this now. If it happens again, feel free to reopen
