### ISSUE TITLE
Gale 1.1.3 installs old versions of some mods

### ISSUE THREAD

**Issue by KleskReaver** [Kesomannen/gale#176]
Gale 1.1.3 is installing old versions of some mods in my modpack even though the modpack manifest points to the latest versions of the mods

Gale itself shows that my modpack dependency list has the correct versions (circled yellow):

![correctversions1](https://github.com/user-attachments/assets/60229080-6684-4ddb-8347-fa99c8001685)
![correctversions2](https://github.com/user-attachments/assets/7db5ce7b-764d-4bd1-95c3-b32406f41707)

but Gale installs these versions instead (circled yellow) and wants me to update to the newer versions:

![actuallyinstalled](https://github.com/user-attachments/assets/5aabd977-8519-4978-8b69-2925c89b9286)

This only happens on Gale 1.1.3, deleting everything out of %appdata% folders (com.kesomannen,gale) in both Local and Roaming folders, uninstalling 1.1.3 and installing 1.1.2 fixes the issue

It also seems to be those specific mods, not sure if that helps

edit: for some more info, game is Lethal Company and modpack is called "LabraCompany"
I don't use Gale itself to create the modpack, I followed a youtube guide on how to make a Thunderstore modpack a year ago and continue to do it that way, has always worked up until Gale 1.1.3

**Comment by ludvdber** [comment]
I have the same issue with Gale 1.1.3. Works fine in 1.1.2

**Comment by Kesomannen** [comment]
Fixed in 1.1.4
