### ISSUE TITLE
Package being extracted improperly

### ISSUE THREAD

**Issue by JarheadHME** [Kesomannen/gale#179]
[This package](https://thunderstore.io/c/gtfo/p/Zag/Sector_11/) gets extracted with all of the containing files in a single folder, instead of retaining its folder structure. I presume it's because `Plugins` is capitalized, but one way or the other it is as it is. Other modmanagers still import properly, so while the package is slightly wrong it'd be nice if gale could handle it as well

**Comment by Kesomannen** [comment]
In my opinion other mod managers are doing the wrong thing here, as many filesystems do differentiate between cases (although windows/NFTS does not by default)

**Comment by JarheadHME** [comment]
I respect that opinion, however the result of some mods working fine on r2mm and not on Gale seems rather bad to me.
