### ISSUE TITLE
Newest Gale Versions Broken on Linux Mint 21

### ISSUE THREAD

**Issue by thelyric27** [Kesomannen/gale#181]
OS Version: Linux Mint 21.1 "Vera"
Affected Gale Versions: 1.1.0 and later
Last Confirmed Working Version: 1.0.1

Similar to issue #177 

I was running an older version of Gale when I tried to update using the in-app updater to try and resolve an issue with Risk of Rain 2 mods not initializing after the Seekers of the Storm update. The download never stopped after over an hour so I closed Gale and reopened it, but it wouldn't launch, just leaving an invisible window. Remained the same after uninstalling and reinstalling the latest version. Some of my friends want to play Lethal Company tonight so after reading issue #177 I decided to brute force it and downloaded appimage versions to test until I found one that worked, being 1.0.1. I then double checked 1.1.0, and checked both the appimage and debian packages for each, 1.0.1 launching and 1.1.0 not. If I could get a pointer to the log locations I'll post them here later.

**Comment by Test-Account666** [comment]
1.1.4 works just fine for me.
Have you tried deleting `~/.local/share/com.kesomannen.gale`?

**Comment by thelyric27** [comment]
Deleting the com.kesomannen.gale folder worked, 1.1.4 is working now. It would seem then that the in-app updater not clearing out old files while updating to versions newer than 1.1.0 from versions older than 1.0.1 is what causes the problem. However, prior to deleting the folder I took the folders containing the mods and mod profiles for my games out and put them back in after a fresh install and they work fine, so there isn't a need to delete and redownload the mod profiles.
