### ISSUE TITLE
Game "GTFO" Mods Downloaded aren't the latest version.

### ISSUE THREAD

**Issue by hawchou1995** [Kesomannen/gale#188]
Hello！

Game "GTFO" Mods Downloaded aren't the latest version.
Need manual updated.

![image](https://github.com/user-attachments/assets/f6623a49-3900-48c9-a6bc-5c0b6b25d747)

**Comment by ShadowyBerry** [comment]
This is just the Rundown not being updated, and has nothing to do with Gale.

**Comment by hawchou1995** [comment]
OK，Thanks for your answer
：)
