### ISSUE TITLE
[Suggestion] Manual Sorting and Custom Seperators

### ISSUE THREAD

**Issue by Foxy1873** [Kesomannen/gale#19]
I have an idea for a new sorting feature. 
Along with the current options, it would be great to add a manual sorting system like the ones in R2MM and TMM.

This could include custom separators, similar to the ones in "Mod Organizer 2." 
These separators might not be shared trough Codes, honestly no idea if that is possible, but they’d make it easier for modpack creators to organize their mods into custom named seperators.

For Example:

## Seperator: API's / Libraries
- BepInEx
- LethalCompanyInputUtils
- loaforcsSoundAPI
- ReservedItemSlotCore

## Seperator: Fixes
- LCMaxSoundFix
- LethalFixes
- EnemySoundFixes

## Seperator: Quality of Life
- ReservedFlashlight
- ReservedWalkie

## Seperator: Sound
- LethalResonance

**Comment by Kesomannen** [comment]
Since a lot of people have requested it, reordering the mods is definitely coming. Not sure about the separators, it would add a lot of complexity, and you can already include/exclude categories for much the same result
