### ISSUE TITLE
Switching games bug

### ISSUE THREAD

**Issue by DropDaDeuce** [Kesomannen/gale#25]
I am using the latest release 0.5.4 and switching games doesn't update the list of options in the include and exclude categories.

**I switched from lethal company to risk of rain and it still shows the lethal company categories in the lists.**

![image](https://github.com/Kesomannen/gale/assets/59843765/951650d8-c53f-4c24-a8c0-664d20c8ff16)

**After switching games closing and reopening gale causes all the categories to disappear.**

![image](https://github.com/Kesomannen/gale/assets/59843765/3a61213e-a451-49c3-acff-6dd2a5d6682c)

**Comment by DropDaDeuce** [comment]
Actually, I can't seem to get any games categories to load other than lethal companies.

So far I have tried loading Risk Of Rain 2, Content Warning, GTFO, and Valheim.

**Comment by Kesomannen** [comment]
Ok, I fixed this for all games except risk of rain. There's something weird with thunderstore's API with just that game 🤔

**Comment by Kesomannen** [comment]
Fixed in 0.6.0
