### ISSUE TITLE
[FEATURE REQUEST] - Reference to Discord Discussion about redesigned Modpack system for Nested Modpack installs.

### ISSUE THREAD

**Issue by Sourceshard** [Kesomannen/gale#26]
https://discord.com/channels/1168655651455639582/1246088342458863618/1246642948037148743

Having an interesting issue since v50.

Some mods have not updated their dependencies. However, mod dependencies have continued to update and move on. The current problem I am facing as a mod pack Dev is the NEED for players to immediately update my Mod Pack after downloading it.

The reason for this is Thunderstore, R2ModMan, and Gale download the manifest as is without comparing mod versions.

Because of the lack of a Load order or a Version check, this leads to for example, a major Library like Lethal Lib being installed at v1.16.0, however, it is also a dependency for a mod at v1.14.0. All of the mod managers will install Lethal Lib v1.16.0, then reinstall over it at v1.14.0 breaking any modpack.

This causes a large amount of unnecessary error reports to Mod Devs, and Mod Pack Devs.

This also means that install times are being Heavily inflated as large Library mods are being downloaded multiple times every time the pack is Downloaded/Imported.

Speaking to @albino (Msg Earballs) I was informed that a Semver system could be included in each mod launcher to correct this problem.
https://devhints.io/semver

I believe this is a critical issue that needs to be resolved for future stability in Lethal Company. This problem will only grow as more updates are released.

As discussed the issue was about not all mods being listed in the Manifest and having other Modpacks present in the manifest.

ebkr had mentioned that they were in discussions for the modpack system to be redesigned.

You had requested that I post this here for future consideration. :D

**Comment by Kesomannen** [comment]
Until thunderstore improves on this, there's not much gale can do about it unfortunately
