### ISSUE TITLE
[FEATURE REQUEST] - Expanded Filter List Catagorys

### ISSUE THREAD

**Issue by Sourceshard** [Kesomannen/gale#27]
The filter list should include Disabled Mods, Depreciated Mods, and Oldest Updated Mods. (for weeding out old mods)

![image](https://github.com/Kesomannen/gale/assets/37197624/2076d91d-61d3-4996-b101-8830c432215d)

**Comment by Kesomannen** [comment]
Umm that's the sorting options, not the filters. You can get oldest updated by sorting by Last updated and Ascending order.

Not sure where to put the disabled and deprecated positive filters, since they wouldn't have the same behavior as the other "Include" filters.

**Comment by Kesomannen** [comment]
Enabled filter has now been added, the others are not coming though
