### ISSUE TITLE
[FEATURE REQUEST] - Modpack Export Template Persistence Per Profile + Config Selection + Changelog

### ISSUE THREAD

**Issue by Sourceshard** [Kesomannen/gale#28]
Exporting a mod as a mod pack should "Save" the last entered data per profile whether or not a mod pack is exported. Those using this feature can open the export tab, make small changes to their existing version and description entries, and pull out a new export.

Since we are aware of the file structure for mod packs we should be able to permanently link a readme, an icon, and select what configs to upload most likely with a separate popup window with checkboxes. (Again all of this should be saved)

Once changes are iterative and persistent, a changelog should be viable. Gale would save the update text to an existing changelog document that it adds to every time mods are updated, replacing duplicate entries of the same mod and expanding the 0.0.0 > 0.0.0 field. Having a version dropdown in the export tab for the config would allow for an auto markdown to be applied that compresses all existing entries into a version header upon selecting a newer version of the game.

**Comment by Kesomannen** [comment]
An overhaul of the modpack export is not really on the top of list right now, but may come in the future. I'd probably make it it's own page (similar to the config editor or mod list).

> Exporting a mod as a mod pack should "Save" the last entered data per profile whether or not a mod pack is exported. Those using this feature can open the export tab, make small changes to their existing version and description entries, and pull out a new export.

Definitely would do.

> ...select what configs to upload most likely with a separate popup window with checkboxes. (Again all of this should be saved)

Sure, the list might get really long though xD

> Once changes are iterative and persistent, a changelog should be viable. Gale would save the update text to an existing changelog document that it adds to every time mods are updated,

This would require it to track every change you make to the profile, which seems complicated. Not sure it's worth the effort, I don't think many people are looking at modpack changelogs anyway.

> replacing duplicate entries of the same mod and expanding the 0.0.0 > 0.0.0 field.

Include that the mod was updated in the changelog? Not exactly sure what you mean by this. 

> Having a version dropdown in the export tab for the config would allow for an auto markdown to be applied that compresses all existing entries into a version header upon selecting a newer version of the game.

What?

**Comment by bananasov** [comment]
> Once changes are iterative and persistent, a changelog should be viable. Gale would save the update text to an existing changelog document that it adds to every time mods are updated,

people could also just use [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) and [git](https://www.git-scm.com/) together with a changelog generator like [git-cliff](https://git-cliff.org/).

**Comment by Kesomannen** [comment]
Almost everything here is implemented, except for the CHANGELOG which I'm afraid won't be coming.

I'll close this now
