### ISSUE TITLE
Missing disabled mods support

### ISSUE THREAD

**Issue by NeatWolf** [Kesomannen/gale#3]
Hi - I'm aware the mod is still in its early stages (it's blazing fast tho, compared to other chrome based modmanagers).

So I'm quite sure this is already on your roadmap - besides:

The -very- first thing I noticed when I imported my profile code is that ALL my mods were enabled - as opposed to just a hundred of them :P 

So I guess my personal unrequested +1 vote on the next must-have feature would be supporting this still unimplemented feature.

(and, have a portable Win64 version .zip of the modmanager :P )

Keep up with the great job!

**Comment by TheBlackEntity** [comment]
I already suggested that in #2 xd

**Comment by NeatWolf** [comment]
> I already suggested that in #2 xd
Yup, I saw you posted a bunch of issues mixed with suggestions in a list that may or may not change.
But, since it felt very personal with some subjective POVs I preferred to file a barebone bug report, 1 issue per post, according to what is "gamebreaking" for me at this stage :)

**Comment by Kesomannen** [comment]
Working on this for 0.3.0 👍

**Comment by Kesomannen** [comment]
https://github.com/Kesomannen/gale/releases/tag/0.3.0
