### ISSUE TITLE
Game will not launch from secondary drive

### ISSUE THREAD

**Issue by SeymourSchlong** [Kesomannen/gale#31]
![image](https://github.com/Kesomannen/gale/assets/36908123/29dc1ee0-5238-4f0f-b8a7-2e14fa6cb668)
(i didnt have this issue before, but im not sure which version introduced it)

my game is located on my secondary drive, and steam on my main drive. there's no option to specify a custom directory for the game either. i havent moved the game and it worked in the past using Gale.

**Comment by Kesomannen** [comment]
This is fixed in 0.5.6 which is releasing very soon
