### ISSUE TITLE
Browse mods search breaks if space at the end of mod name

### ISSUE THREAD

**Issue by DiFFoZ** [Kesomannen/gale#34]
If search for example mod `BlueArchivePlayerModel` then it will find, but if add space after the name, then it will not find it.

Expected (like r2modman do):
![image](https://github.com/Kesomannen/gale/assets/48765566/71fd1a28-4f0b-4dc2-9265-a7dcafebe083)

Actual:
![image](https://github.com/Kesomannen/gale/assets/48765566/16ab5f15-3f81-4ec2-bbd1-666fccc22202)

**Comment by Kesomannen** [comment]
Fixed in 0.6.0
