### ISSUE TITLE
[feature request] Easier scrolling to the bottom

### ISSUE THREAD

**Issue by MathiusXII** [Kesomannen/gale#38]
In r2modman I could either drag the bar all the way to the bottom or click and hold at the bottom of the scroll bar and it'd scroll down for me.

With Gale, I can't drag it to the bottom since it seems to load more in as you scroll which resets the scroll bar.
Clicking and holding at the bottom is glitchy and doesn't work consistently. Sometimes it'll just stop scrolling at a loading point.

A button to scroll to the bottom or just a fix for these issues would be much appreciated!

**Comment by Kesomannen** [comment]
Anything related to scrolling is quite finicky and difficult to control. Add to that the fact that the list is virtual - i.e. all the mod cards don't actually, but instead a few elements are moved as you scroll - which all makes it really annoying to work with. All in all I don't think it's worth for a tiny QoL change like this.

Maybe I'll have a crack at it sometime in the future, but not right now.
