### ISSUE TITLE
[Suggestion] Add "Disabled" to the "Include" dropdown in the profile mod list.

### ISSUE THREAD

**Issue by SeymourSchlong** [Kesomannen/gale#39]
There's currently no way to either sort mods to have the disabled ones at the end, or to completely hide them. 

I think that having them be toggleable here would be good.
![image](https://github.com/Kesomannen/gale/assets/36908123/c9d77479-7d6a-4637-bd36-1ab41877fb5e)

If possible, a way to have them be sent to the bottom of the list would also be appreciated.

**Comment by Kesomannen** [comment]
I'll add a toggle for it 👍
