### ISSUE TITLE
[Profile codes] Add support to profiles with local mods

### ISSUE THREAD

**Issue by CatsArmy** [Kesomannen/gale#4]
atm it doesnt let you import the profile if it has a imported mod installed and just notifies me that the mod was not found on thunderstore

**Comment by Kesomannen** [comment]
Hi, this doesn't seem to be supported by any other mod manager nor Thunderstore themselves

https://github.com/ebkr/r2modmanPlus/wiki/Profiles#exporting-your-profile

I could add it as an exclusive feature to Gale, but not sure if it's worth it just for that.

**Comment by CatsArmy** [comment]
I am pretty sure it is could be wrong tho

**Comment by Kesomannen** [comment]
Ebkr confirmed it isn't in r2modman (https://discord.com/channels/1168655651455639582/1246088342458863618/1246216458787229737) and that's by design due to security concerns. So sadly this is not coming.
