### ISSUE TITLE
DLL's from what seems to be random plugins and patchers are getting installed in the wrong place.

### ISSUE THREAD

**Issue by broken-usb** [Kesomannen/gale#41]
Before the fix "BepInEx/* directories in local mods being installed at the wrong location" i was able to install plugins and patchers for bepinex just fine but now they get installed in the wrong directory.

The current version creates another BepInEx folder inside the BepInEx folder:
![image](https://github.com/Kesomannen/gale/assets/50057556/62d0b663-08db-4a22-9478-b45a6dd248a7)

Inside this folder there is only the "patchers" and "plugins" folder and it seems like when installing mods a random selection gets installed on this duplicate BepInEx folder, this mods simply will not work.

Here is a list of mods i have for LethalCompany(code: 019073a2-b3fe-e0f4-16b8-af06e7cc035f)
![image](https://github.com/Kesomannen/gale/assets/50057556/fb8a3d45-05fb-496e-adbf-9d49b2481ad4)

And here is a screenshot of the mods that for some reason got installed in the duplicate folder(none of these mods will work)
![image](https://github.com/Kesomannen/gale/assets/50057556/dc6470f3-c91a-4319-9e82-4566c1085ce3)

But turns out that what is happening is that the Modmanager is separating the DLL's from the actual mods(and patchers), checking the plugins that got installed into the duplicate folder you will see that they only contain the DLL for the mod and the rest of the files such as the README or ICON get dowloaded in the right BepInEx folder, mods that ONLY got dowloaded to the original folder will contain their DLL as they are supossed to.

For example, PathfindingLagFix got installed to the duplicate folder, checking its folder you will see that the DLL is missing:
![image](https://github.com/Kesomannen/gale/assets/50057556/91021579-66c6-48fd-857f-49c779e406e2)
And the DLL is all by itself on the duplicate folder:
![image](https://github.com/Kesomannen/gale/assets/50057556/577ad49c-f7d3-42e2-9fd6-644bc99948b5)

This doesnt happen with mods that didnt get installed on the duplicate folder, an example being ButteryFixes:
![image](https://github.com/Kesomannen/gale/assets/50057556/56eccec4-d54c-4d07-a1a0-58d2b6b53d5b)

The issue doesn't just happen with profiles created before the update, it also happens with newly created profiles, not sure if this also happens with other games since i havent tested that out.

**Comment by Kesomannen** [comment]
Hi, this is happens for mods with BepInEx/plugins folders. I've made a quick hotfix for it, which is being published right now.
