### ISSUE TITLE
Cannot enable mods if a dependency isn't installed

### ISSUE THREAD

**Issue by Teacyn** [Kesomannen/gale#42]
...While this is probably intended behavior, it's inconsistent given that you can enable mods without their dependencies if it is installed, but disabled. Here's some screenshots showing it using View Extension. View Extension is not an actual hard dependency for moon mods (rather, they just look wrong if it's not installed), so I use CullFactory to accomplish the same thing and not keep a redundant mod, but Gale won't let me do that.

Here's the intended, functioning behavior when ViewExtension is disabled.
![Gale_cN36pDcahe](https://github.com/Kesomannen/gale/assets/12898157/7bc7a4d3-032c-4852-b55b-8e85b59155d9)

And if I uninstall ViewExtension instead of disabling it, I become unable to force-enable the moon.
![Gale_eTB7eQeR7I](https://github.com/Kesomannen/gale/assets/12898157/0bacc71b-992a-4610-a67d-96d24b6c888a)

While the slider becomes green, the moon is not actually enabled.

**Comment by Kesomannen** [comment]
Fixed in 0.6.2
