### ISSUE TITLE
[FEATURE REQUEST] - Shortcuts to specific profiles

### ISSUE THREAD

**Issue by Slugiish** [Kesomannen/gale#44]
I'd like to request a way to make shortcuts that directly lead to a game and profile without having to open the mod manager and navigate there. Here's a link to a feature request for the same feature in r2modman's github.

https://github.com/ebkr/r2modmanPlus/issues/448

Not sure if this is possible to add but I wanted to mention it just in case it is.

**Comment by Kesomannen** [comment]
Definitely possible, I was actually planning to do it. Will hopefully come in the next update :D

**Comment by Kesomannen** [comment]
Added in 0.7.0 (https://github.com/Kesomannen/gale/wiki/CLI)
