### ISSUE TITLE
[FEATURE REQUEST] Ignore Mod Updates

### ISSUE THREAD

**Issue by viiuan** [Kesomannen/gale#46]
When building modpacks for previous game versions, or if you simply prefer a specific old version of a mod, it would be useful to be able to mark a mod as ignored for updates so you don't get the update popup at the top every time.

**Comment by MoonJuiceDev** [comment]
+1

Bonus points if the blacklist/ignore is saved into the pack when sharing a mod code/file, so that everyone can Update All without worrying about the one mod update that breaks everything :)

**Comment by viiuan** [comment]
AWESOME idea honestly, one of the first times i shared a modpack with someone for v50 when v56 was already out, they just pressed the update button immediately :sob: (yes they were using gale)

**Comment by Kesomannen** [comment]
Added in 0.7.3
