### ISSUE TITLE
Markdown does not properly support <details>

### ISSUE THREAD

**Issue by viliger2** [Kesomannen/gale#49]
It seems that markdown implementation not only doesn't support collapsing of `<details>` block, it also kinda breaks when there are multiple multilevel lists in the same markdown file. 
Example link: https://thunderstore.io/package/viliger/Catacombs/changelog/, how it should look:
![image](https://github.com/user-attachments/assets/a5aca472-2085-4cd6-b546-c0a55bb0a02a)
How it looks in the app:
![image](https://github.com/user-attachments/assets/4c714357-bfc7-4fac-9685-335f2b22a026)

**Comment by Kesomannen** [comment]
This is an issue with the markdown library gale is using. I'll make an issue in that repo about it

**Comment by Kesomannen** [comment]
Hmm, with some more testing seems like it works fine if I render a string literal with <details> tags. Must be something wrong with the fetching then..

**Comment by Kesomannen** [comment]
Finnaly fixed in 0.8.1
