### ISSUE TITLE
I can get quite far on MacOS but I get the error: Failed to execute 'launch_game' - "BepInEx preloader not found at"

### ISSUE THREAD

**Issue by logiota** [Kesomannen/gale#54]
Great work!
I can get quite far on MacOS but I get the error: 
14:57:30 [INFO] launching from steam with command: "/Applications/Steam.app" "-applaunch" "892970" "--dorstop-enable" "true" "--doorstop-target" "/Users/user/Library/Application Support/com.kesomannen.gale/valheim/profiles/Default/BepInEx/core/BepInEx.Preloader.dll"
14:57:30 [ERROR] Failed to execute 'launch_game': Permission denied (os error 13).

to get it to launch try to launch:
in the Terminal :
xattr -d com.apple.quarantine /Applications/Gale.app 
in System Settings I added Gale to Full Disk Access:
![Screenshot 2024-07-22 at 16 46 46](https://github.com/user-attachments/assets/d62ad9cd-0a2f-4c03-947c-42fbea49b8e3)

feel free to use this for the 'MacOS install instructions' in your readme

**Comment by Kesomannen** [comment]
👍
