### ISSUE TITLE
"About" menuitem - or any way to determine which version you're using

### ISSUE THREAD

**Issue by NeatWolf** [Kesomannen/gale#6]
Hi,

I believe it's pretty basic but today I launched my local copy of the manager and read about the (updated) changelog.

And yet.

Did it mean my installed copy got updated? (probably not, it probably opens a remotely hosted changelog).
I could not tell as there was no easily accessible way showing the installed version of the modlauncher.
(ok, in this case I could probably tell I was using v0.2, but in the future's going to be an issue)

Besides, from the POV of the average (dumb :P) user, there's no way to determine that.

Could you please add the currently version of the modmanager in a very visible spot (title bar?) - maybe even in the Help->About... mandatory menuitem+popup?

That would be a good place where to find a link to the most recent release of the editor.
This could probably could be the base on where to build a "you're using an older version, current version is XX - do you want to get the new release? Here's the link" modal popup when you launch the modmanager.

**Comment by Kesomannen** [comment]
Yes, the changelog is just a link to the CHANGELOG.md on Github. I could make a copy of it and include it in the build, so it would be local instead. But then I would have to maintain that and that just seemed annoying.

The updates should in theory install automatically (through tauri's auto updater), which I know isn't working. Just a bit clueless on how to even debug the issue, but will definitely need to have it fixed for the stable release. For now, you have to uninstall the previous version (make sure to **not** check "remove application data" box), and install the newer version manually :/

In 0.3.0 I did add a text to the bottom right corner displaying the version.
