### ISSUE TITLE
[Suggestion] List dependant mods within a modpack

### ISSUE THREAD

**Issue by Abjectee** [Kesomannen/gale#60]
Currently I can click on [mod A] to see that it depends on [mod B]. But not the other way around.

Sometimes new dependencies are added when mods update and a new mystery mod pops up in my modlist and as it stands I'll have to click through each mod to see which one needs it.

**Comment by Abjectee** [comment]
As I just posted this I realized that I can simply disable the mod in question to see its dependants. 
Still, I think it would be more intuitive to have them listed the same way dependencies are.

**Comment by Kesomannen** [comment]
![bild](https://github.com/user-attachments/assets/a8066ffc-a11f-4535-a049-a4b5a90933de)
It's up here
