### ISSUE TITLE
Version 0.7.0 does not correctly select the "steam" executable path

### ISSUE THREAD

**Issue by AlanCratys** [Kesomannen/gale#63]
When I select the executable file path correctly, the error window provides the following error message:
"Failed to set prefs - Invalid args `value` for command `set_prefs`: invalid type: map, expected path string."
<img width="693" alt="{07579FE7-8F1F-4e5d-B8DA-60CAB5649FDC}" src="https://github.com/user-attachments/assets/a002eed4-35cf-4224-bdd8-b6bb76fbd804">
![image](https://github.com/user-attachments/assets/da9f7001-0db3-4632-910e-64c30f7563db)
<img width="632" alt="{2ECD6DDC-F78F-4fa7-9C6F-CEEFD875C30D}" src="https://github.com/user-attachments/assets/5fa839c5-e197-43d2-becb-6c4bb56b22d6">

**Comment by Kesomannen** [comment]
Fixed in 0.7.1. Auto-updater is however not working so you'll have to update manually
