### ISSUE TITLE
Select a softlock for the path of the executable file or folder

### ISSUE THREAD

**Issue by AlanCratys** [Kesomannen/gale#64]
In version 0.7.1, I can't change any executable file or folder path in the settings, even if I make a selection, it doesn't take effect in Gale.
<img width="733" alt="{558D2728-59E3-46c8-A3CD-ED879342C85F}" src="https://github.com/user-attachments/assets/2b6e376f-c8fc-4f31-9c0d-6132fcfea0ec">
<img width="740" alt="{B7095B52-CAE6-4002-9F47-8599F89A885B}" src="https://github.com/user-attachments/assets/70cbf708-7566-45d6-ad7f-81bb03dfdf73">

**Comment by AlanCratys** [comment]
![image](https://github.com/user-attachments/assets/4f165be6-1a79-42bb-bc37-82fed70f6dad)
Changing the path seems to have a very high latency, and often fails, just now I tried to change the folder path in five minutes to succeed, but now I can't change it back.

**Comment by AlanCratys** [comment]
In addition, reading the config directory in the original reserved package in version 0.7.1 will cause a crash, and it will take a long time to ensure that the new version is able to read and be compatible with the config folder retained in version 0.6.2

**Comment by NakiriFox** [comment]
same issue

**Comment by Kesomannen** [comment]
Should be fixed in 0.7.2
