### ISSUE TITLE
Manager opens with a blank box then closes within a few seconds.

### ISSUE THREAD

**Issue by WaveRoot** [Kesomannen/gale#65]
Everything was working fine for the first few minutes, then I started to get this error `Failed to create profile - Failed to save manager state: The system cannot find the path specified. (os error 3).` when creating profiles and errors similar to it when I tried to switch or delete profiles. I closed the manager and then re-opened, and now all it does is open briefly with a transparent box and then close. I've tried running in administrator mode and using compatibility settings and it did not work. I also tried installing an older version of the manager and that also didn't work.

**Comment by Kesomannen** [comment]
Can you check the logs, under AppData/Roaming/com.kesomannen.gale

**Comment by WaveRoot** [comment]
Fixed for now it seems. I deleted the com.kesomannen.gale folder under appdata/roaming and everything works great right now.
