### ISSUE TITLE
Override game directory not working.

### ISSUE THREAD

**Issue by 2690Cody** [Kesomannen/gale#66]
I click on it to set to a different directory, since Lethal Company is stored on my D: drive, while Steam is on my C: drive.

I click "Select Folder", and nothing happens. I've tried numerous times, restarted the application, and even tried running it as admin. just stays as "Not set"

**Comment by 2690Cody** [comment]
ah my bad, same issue as #64

**Comment by Kesomannen** [comment]
Should be fixed in 0.7.2
