### ISSUE TITLE
When typing text in the search bar, the scrollbar should be reset to the top

### ISSUE THREAD

**Issue by NakiriFox** [Kesomannen/gale#67]
![QQ_1722537085176](https://github.com/user-attachments/assets/a1d0526a-bc3b-4dc2-bc7d-74d30fdc1ce0)

example: This is what should be displayed to the user👇
![QQ_1722537095725](https://github.com/user-attachments/assets/04d42ec8-df46-4974-b2e5-4449679aec89)

**Comment by Kesomannen** [comment]
Fixed in 0.8.11
