### ISSUE TITLE
[Suggestion] mod downloaded indicator in mod browsing and uninstall button on condensed mods

### ISSUE THREAD

**Issue by Omegathenotsofunnyman** [Kesomannen/gale#74]
r2 and thunderstore already have this, showing a checkmark at the rightside of the mod when already downloaded
![image](https://github.com/user-attachments/assets/55c95161-757b-4381-a614-12c0d12525a0)

it would be nice if something similar was added back instead of having to check the expanded section
![image (26)](https://github.com/user-attachments/assets/bd2cd53d-fb7b-42db-b821-85adb3f540b0)

i would also like to suggest an unintall button on the condensed mods

example:
![image (20)](https://github.com/user-attachments/assets/1fbf87b1-f195-48b3-a0ed-a4396c57ce18)

**Comment by Snooziepup** [comment]
This would be a great feature, manager is kind of a pain to use without it
