### ISSUE TITLE
Failed to launch Dyson Sphere Program

### ISSUE THREAD

**Issue by NakiriFox** [Kesomannen/gale#77]
![image](https://github.com/user-attachments/assets/b66c0ad5-04b0-452f-b357-439bce78ded9)
Selected the correct path and did not install any mods.

**Comment by Kesomannen** [comment]
It's supposed to be SteamLibrary, not SteamaLibrary/steamapps. You also need BepInEx installed to launch the game

**Comment by NakiriFox** [comment]
![image](https://github.com/user-attachments/assets/5f030168-d358-4ece-b36a-4694561694a9)
![image](https://github.com/user-attachments/assets/c7eec133-7976-4410-ae33-f55360196412)
![image](https://github.com/user-attachments/assets/25c304e3-a445-43d8-bd5d-82dc189a0eac)
Not working :(

**Comment by NakiriFox** [comment]
![image](https://github.com/user-attachments/assets/a9803820-7c22-4a8b-af56-499eb5352f81)
Modmanager did not install BepInEx correctly.

When I manually placed BepInex into the directory, the problem was resolved.
![image](https://github.com/user-attachments/assets/823c3823-eeb8-4fc4-9d87-3dbe41e6a15a)

**Comment by Kesomannen** [comment]
Ah, I see. The Dyson Sphere Program BepInEx package is just called BepInEx, while gale recognizes it only if it starts with "BepInExPack". I'll fix that asap

**Comment by Kesomannen** [comment]
Fixed in 0.7.5
