### ISSUE TITLE
Profile is Borked, and I don't know why

### ISSUE THREAD

**Issue by fruitmeister101** [Kesomannen/gale#79]
![image](https://github.com/user-attachments/assets/642a01ec-a343-4c49-90b0-4c6f2766b8cd)
Clicking on  Manage Profile brings up a blank page and several copies of this error. Idk whats wrong, but it's very annoying. You probably already know about it and are working on it, and for that -- thanks.

**Comment by Kesomannen** [comment]
Are you on an old version?

**Comment by Kesomannen** [comment]
Yeah, I can see you're on an older version. Manually update to the newest version and this will be fixes
