### ISSUE TITLE
[FEATURE REQUEST] Launch modded from Steam

### ISSUE THREAD

**Issue by BroBoss64** [Kesomannen/gale#80]
R2modman has a feature where it will generate a launch option to launch the game modded through Steam instead of the mod manager. This works with gale if manually set up, but it would be more convienent to generate it automatically.

 `--doorstop-enable true --doorstop-target "C:\Users\{USER}\AppData\Roaming\com.kesomannen.gale\{GAME FOLDER}\profiles\{PROFILE NAME}\BepInEx\core\BepInEx.Preloader.dll"`

**Comment by Damglador** [comment]
Apparently its not always `--doorstop-target`, Risk of Rain 2 works only with `--doorstop-target-assembly`

**Comment by Kesomannen** [comment]
Gale already does this under the hood when launching so should be pretty simple to add

**Comment by Kesomannen** [comment]
Added in 0.8.0
