### ISSUE TITLE
Strange issues launching H3VR with Gale

### ISSUE THREAD

**Issue by CherenTheCat** [Kesomannen/gale#81]
I switched to Gale due to having a bunch of issues with r2modman, and I imported all my mod lists, but with H3VR specifically, I get breaking errors I don't get with r2, that cause most of my mods to not load, and makes me completely unable to actually play. Due to this, I am having to use r2 for specifically H3VR.

Attached are both my Gale and r2 BeipInEx logs, in case they give any insight into this.
[GaleLogOutput.log](https://github.com/user-attachments/files/16683095/GaleLogOutput.log)
[r2LogOutput.log](https://github.com/user-attachments/files/16683097/r2LogOutput.log)

**Comment by Kesomannen** [comment]
Seems like FixPluginTypesSerialization is failing somehow, will look into it

**Comment by Kesomannen** [comment]
Ok I think I fixed it, try updating gale to 0.7.6 and reinstalling Sodalite. I can't test myself since I don't have the game

**Comment by CherenTheCat** [comment]
I had to reinstall HookGenPatcher along with Sodalite, but it seems to be working now!

[Cheren Alexander - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=2qmbm3)	[2qmbm3]

On August 22, 2024 at 19:31 GMT, Kesomannen ***@***.***> wrote:

Ok I think I fixed it, try updating gale to 0.7.6 and reinstalling Sodalite. I can't test myself since I don't have the game

**Comment by Kesomannen** [comment]
Nice!
