### ISSUE TITLE
When setting Data, Temp or Download Cache Directories presented with error

### ISSUE THREAD

**Issue by ReidWeb** [Kesomannen/gale#83]
When attempting to set data, temp, and download cache directories to paths as follows

```
E:\Gale\Data
E:\Gale\Temp
E:\Gale\Cache
```

I am presented with the following error:
```
`Failed to set prefs - The system cannot find the path specified. (os error 3).`
```

Gale download manager itself is installed in `E:\Gale\Install`.

Sorry this is difficult issue to produce a minimum reproducible example for!

---

## OS spec

Edition	Windows 11 Pro
Version	23H2
OS build	22631.4037
Experience	Windows Feature Experience Pack 1000.22700.1027.0

**Comment by Kesomannen** [comment]
Can you confirm if it's fixed in 0.7.6?

**Comment by ReidWeb** [comment]
Was able to set Data directory after updating; can't update Cache directory

**Comment by Kesomannen** [comment]
The cache directory setting is gone in 0.8.0 so I guess I'll close this
