### ISSUE TITLE
Add a fallback launch option for Enter The Gungeon (For Direct launch mode, Linux)

### ISSUE THREAD

**Issue by Damglador** [Kesomannen/gale#84]
Enter The Gungeon has a native Linux version, it requires some work to function properly with mods, but the main thing is that it has to be launched with `start_game_bepinex.sh` instead of executable, and there's no .exe file in the game directory.
`start_game_bepinex.sh` accepts launch parameters from Gale that makes it work with mod manager profiles instead of BepInEx in the game directory.
I made it work by just renaming the script to `EtG.exe`, but would be much easier if Gale just tried to launch `start_game_bepinex.sh` after not being able to find  `EtG.exe`. That shouldn't be hard to implement, I could test it if needed.

**Comment by Kesomannen** [comment]
Should be fixed in 0.8.10

**Comment by Damglador** [comment]
> Should be fixed in 0.8.10

Not quite https://github.com/Kesomannen/gale/issues/134 I can't even test if it's trying to grab .exe or start_game_bepinex.sh, or .x86, it just doesn't launch with either of those present

**Comment by Damglador** [comment]
btw launching EtG in particular (idk how it is with other games) with `.x86` or `.x86_64` have no sense, because mods can be loaded only if it's launched with `start_game_bepinex.sh`. I couldn't find any other workaround to make it work with direct launch from .x86 .x86_64 or with Steam, only `start_game_bepinex.sh` is able to make it load mods.

Just in case, here's the start_game_bepinex.sh:
[start_game_bepinex.txt](https://github.com/user-attachments/files/17355337/start_game_bepinex.txt)
