### ISSUE TITLE
Last updated time shows NaN seconds

### ISSUE THREAD

**Issue by gusruben** [Kesomannen/gale#85]
The "Last updated" time for all mods in all games shows as "NaN seconds".

![image](https://github.com/user-attachments/assets/9dc66eb7-e31f-484d-96f8-a42e9b47c2ed)

**Comment by Kesomannen** [comment]
Are you on Linux?

**Comment by tisajokt** [comment]
> Are you on Linux?

I believe they are, and I have this issue on Linux as well.

**Comment by gusruben** [comment]
I am on Linux. I did a bit of debugging, and it seems like some dates are being interpreted as invalid in Tauri/Gale while the same date works fine in vanilla Chrome or Firefox:
(Tauri)
![image](https://github.com/user-attachments/assets/0b4e5748-6802-4d39-a83f-68e694868b15)
(Chrome)
![image](https://github.com/user-attachments/assets/0f0fb711-1dbe-437a-964a-e366889b2e20)
(Firefox)
![image](https://github.com/user-attachments/assets/1c516647-adc3-47f9-9cca-9742aba57534)

It seems like the problem is the `UTC` at the end of the date, so an (admittedly hacky) fix could be to manually add the offset:
![image](https://github.com/user-attachments/assets/a026741e-3546-45a8-a392-c454460b5166)

**Comment by notpeelz** [comment]
Fixed by #114
