### ISSUE TITLE
[Feature Request] Add menu for adding custom game launch commands, for example Unity commands, like r2modman

### ISSUE THREAD

**Issue by Snooziepup** [Kesomannen/gale#89]
R2ModMan's looks like this:
![image](https://github.com/user-attachments/assets/1aa5d9ff-a904-4895-9ba4-0c6fc0e277dc)

**Comment by Damglador** [comment]
I think it was added in 0.8.something, under Profile menu

**Comment by Kesomannen** [comment]
It allows you to copy them but not modify
