### ISSUE TITLE
[Suggestion] Add counters for mods in profile and online

### ISSUE THREAD

**Issue by yumm-dev** [Kesomannen/gale#9]
Like in the Thunderstore and r2modman managers, each have counters that show how many mods are in the current profile and how many exist online. This feature seems to be missing from Gale, and it would be quite useful if it was added.

**Comment by Kesomannen** [comment]
Maybe, I'm not sure where to put it though.

**Comment by Kesomannen** [comment]
![bild](https://github.com/Kesomannen/gale/assets/113015915/025fd0c4-54b5-4937-bcae-0efb81255e04)
Of course I could have it like this, but I think it looks kind of bad. I don't really want to expand either.

**Comment by Test-Account666** [comment]
![screenshot1~2.png](https://github.com/Kesomannen/gale/assets/36412486/7bb84324-2d0a-412d-a0fd-99bbc09c8150)

Maybe you could move the filter button?
