### ISSUE TITLE
LethalLevelLoader not showing full config

### ISSUE THREAD

**Issue by gusruben** [Kesomannen/gale#93]
The config for LethalLevelLoader, which should have many more options for different moons and interiors, only has one section.

![image](https://github.com/user-attachments/assets/4e87f551-9887-4dc6-b8c2-2b3412cef4f8)

This worked very recently, but after opening and closing the game it appears to have stopped.
Here's my `LethalLevelLoader.cfg`: https://katb.in/epofebawavo
It may or may not be intended, but there are 9 zero-width spaces preceding each config section name.

**Comment by Kesomannen** [comment]
This is because of a LLL issue that will be fixed soon
